setwd("C:\\Users\\Joe\\_LEARNING_todo\\___Data Science\\4 Exploratory Data Analysis\\Course Project 1\\ExData_Plotting1\\")
dataSet <- read.table("household_power_consumption.txt", header=TRUE, sep=";")
subdataSet <- subset(dataSet,(dataSet$Date == "1/2/2007"|dataSet$Date == "2/2/2007"))
library(datasets)
subdataSet$tempGlobal_active_Power <- as.numeric(as.character(subdataSet$Global_active_power))
subdataSet$DateTime <- as.POSIXct(paste(subdataSet$Date, subdataSet$Time), format="%d/%m/%Y %H:%M:%S")
png(filename="plot3.png",width = 480, height = 480, units = "px")
par(mfrow=c(1,1),mar=c(2,2,1,4))
plot(subdataSet$DateTime,as.numeric(as.character(subdataSet$Sub_metering_1)), type="l", xlab="", ylab="Energy sub metering")
legend("topright", pch="____", col = c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
lines(subdataSet$DateTime,as.numeric(as.character(subdataSet$Sub_metering_3)), col="blue", type="l", xlab="", ylab="Energy sub metering")
lines(subdataSet$DateTime,as.numeric(as.character(subdataSet$Sub_metering_2)), col="red", type="l", xlab="", ylab="Energy sub metering")

##dev.copy(png, file = "plot3.png")
dev.off()